conversion =[
    (r'\'\'\'', 'TRIPLE_QUOTE'),
    (r'\"\"\"', 'TRIPLE_QUOTE'),

    (r'\=', 'EQUAL'),
    (r'\+', 'PLUS'),
    (r'\-', 'MINUS'),
    (r'\*', 'MULTIPLY'),
    (r'\/', 'DIVIDE'),
    (r'\*\*', 'POWER'),
    (r'\%', 'MOD'),
    (r'\/\/', 'FLOOR_DIVIDE'),
    (r'\[', 'LB'),
    (r'\]', 'RB'),
    (r'\(', 'LP'),
    (r'\)', 'RP'),
    (r'==', 'DOUBLE_EQUAL'),
    (r'!=', 'NOT_EQUAL'),
    (r'>=', 'GRATER_THAN_OR_EQUAL'),
    (r'<=', 'LESS_THAN_OR_EQUAL'),
    (r'<', 'LESS_THAN'),
    (r">", "GREATER_THAN"),
    (r'\n', 'NEWLINE'),
    #iteration
    (r'while\s', 'WHILE'),
    (r'while\(', 'WHILE'),
    (r'for\s', 'FOR' ),
    (r'is\s', 'IS'),
    (r'with\s', 'WITH'),
    (r'open', 'OPEN'),
    (r'range', 'RANGE'),
    (r'in', 'IN'),
    (r'print', 'PRINT'),

    #conditional
    (r'\sor\s', 'OR'),
    (r'\sand\s', 'AND'),
    (r'not', 'NOT'),
    (r'True', 'TRUE'),
    (r'False', 'FALSE'),
    (r'None', 'NONE'),

    (r'if\s', 'IF'),
    (r'if\(', 'IF'),
    (r'elif\s', 'ELIF'),
    (r'elif\(', 'ELIF'),
    (r'else', 'ELSE'),

    #khusus
    (r'break\n', 'BREAK'),
    (r'continue\n', 'CONTINUE'),
    (r'try', 'TRY'),
    (r'except', 'EXCEPT'),
    (r'raise\s', 'RAISE'),
    (r'pass', 'PASS'),
    (r'def\s', 'DEF'),
    (r'return\s', 'RETURN'),
    (r'class\s', 'CLASS'),
    (r'from\s', 'FROM'),
    (r'import\s', 'IMPORT'),
    (r'as\s', 'AS'),

    (r'int', 'TO_INT'),
    (r'float', 'TO_FLOAT'),
    (r'str', 'TO_STR'),
    (r'bool', 'BOOL'),
    (r'abs', 'ABSOLUTE'),
    (r'round', 'ROUND'),
    (r'pow', 'POW'),
    (r'input', 'INPUT'),

    #DATA_TYPE
    (r'\d+', 'INT'),
    (r'\d+\.\d+', 'FLOAT'),
    (r'\".*\"', 'STR'),
    (r'\'.*\'', 'STR'),
    (r'[a-zA-Z_]\w*', 'VAR'),
    (r'\s', 'BLANK'),
    (r'\,', 'COMMA'),
    (r'\.', 'METHOD'),
    (r';', 'SEMICOLON'),
    (r':', 'COLON'),
    (r'\#.', 'COMMENT'),
    (r'\w', 'NULL'),
        (r"\S", "UNDEF")
]